### ISSUE TITLE
"Calculate" button doesn't work

### ISSUE THREAD

**Issue by FlyingGMM** [iamcal/enchant-order#1]
Hi,
Clicking the 'Calculate' button only works rarely for me. I don't know what the issue is; the only solution I found is refreshing the page, which makes it work only about 10% of the times I try.

Is there something I'm doing wrong?

**Comment by iamcal** [comment]
What browser are you using? Can you open the developer console and copy & paste any errors you get?

**Comment by robertpainsi** [comment]
![image](https://user-images.githubusercontent.com/1794599/126140215-da959ee3-b6d9-4ef8-84b7-b518637a281d.png)

Same issue.
My old laptop only has a resolution of 1600 x **900**. So the footer is partially covering the _Calculate_ button on smaller screens.

**Comment by iamcal** [comment]
aha, great find! i've fixed this so that the footer won't overlap the button. thank you
