### ISSUE TITLE
How about renaming? :D

### ISSUE THREAD

**Issue by DTRW919** [iamcal/enchant-order#10]
When I was making my helmet, it came out as too expensive when I renamed it as well. If you could add that as a stage it'd be perfect, rn Im using the 1.14.1 only thing as a workaround. Thanks!

**Comment by iamcal** [comment]
Just rename during one of the combining steps - it's free and doesn't add to the work cost

**Comment by DTRW919** [comment]
I thought that renaming at any time cost 1 level and added a cost
