### ISSUE TITLE
Feature Request: Enchanting Books

### ISSUE THREAD

**Issue by Wizard12892** [iamcal/enchant-order#16]
A potentially useful feature (at least for myself) would be the option to combine books without applying to armor or tools.

I'm not sure if it's the same order as listed just without the base item or if it's a separate calculation.

**Comment by Nebulacrity** [comment]
Thirding this. Can be useful for determining how to create an Enchanted Book with all enchantments (and curses, when support for those gets added) on it at once.

**Comment by iamcal** [comment]
This has been added - select "Book" at the bottom of the enchantable items list 👍
