### ISSUE TITLE
Bug: Unoptimal enchantment order

### ISSUE THREAD

**Issue by bennett-zhang** [iamcal/enchant-order#18]
## How to Reproduce

Select boots and the following enchantments:

- Blast Protection 4
- Depth Strider 3
- Feather Falling 4
- Mending 1
- Thorns 3
- Unbreaking 3

### The result is as follows:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/20321329/210116297-38f8c85e-a02f-4b32-8948-887e02d3ad44.png">

However, that is **NOT** the optimal solution.

### Here is a better enchantment order:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/20321329/210116372-8a2bd5b4-2b4d-40a2-afc6-9d34c671e206.png">

As you can see, the total cost between the two solutions are _both_ 53 levels. So how is the second solution better?

Well, let's break down the individual costs of combining each enchantment.

### First solution:

- Boots + Blast Protection 4 **(8 Levels)**
- Boots + Depth Strider 3 **(7 Levels)**
- Feather Falling 4 + Mending 1 **(2 Levels)**
- Boots + (Book with Feather Falling 4 + Mending 1) **(10 Levels)**
- Thorns 3 + Unbreaking 3 **(3 Levels)**
- Boots + (Book with Thorns 3 + Unbreaking 3) **(23 Levels)**

8 + 7 + 2 + 10 + 3 + 23 = **53 Total Levels**

### Second solution:

- Boots + Thorns 3 **(12 Levels)**
- Blast Protection 4 + Mending 1 **(2 Levels)**
- Boots + (Book with Blast Protection 4 + Mending 1) **(12 Levels)**
- Depth Strider + Unbreaking 3 **(3 Levels)**
- Boots + (Book with Depth Strider + Unbreaking 3) **(13 Levels)**
- Boots + Feather Falling 4 **(11 Levels)**

12 + 2 + 12 + 3 + 13 + 11 = **53 Total Levels**

You see even though both solutions use the same number of total levels, the final step in the first solution requires a whopping 23 levels! On the other hand, in the improved second solution, you only need at most 13 levels at any time (for the second to last step).

This is super important, because the way EXP scales with Levels in the game is *not linear*! The higher a Level you are, the harder it is to gain additional Levels. To put things in perspective, going from Level 30 to Level 40 takes about the same EXP as going from Level 1 to Level 26!

With a few changes to your code, I have fixed this issue to always find the optimal combination of enchantments to minimize EXP in addition to minimizing Levels. I will submit a pull request.

Cheers!

**Comment by ksulli** [comment]
Sorry for the drive-by comment, but I looked at the diff in your pull request because I was interested in what you did, but its a lot of whitespace changes, forgotten comments etc. Could you clean it up so the diff shows the actual changes? A good idea would also be to use `git rebase -i`  to squash all your commits and get rid of the accidental commit (and subsequent delete) of the .DS_store file.
