### ISSUE TITLE
Option to calculate Thorns III as 2x Thorns II

### ISSUE THREAD

**Issue by ksulli** [iamcal/enchant-order#20]
According to the wiki, [obtaining Thorns III](https://minecraft.fandom.com/wiki/Thorns#Obtaining) directly can be a bit complicated, because villagers only sell Thorns II, so often the player will need to somehow combine two Thorns II books (I guess the same argument could be made for Swift Sneak and Soul Speed).

Do you think it would be possible to add a way to say that I want the enchantment order including combining the same book? Or is the impact of combining thorns books negligible?

**Comment by randallbruder** [comment]
Re-read the Wiki article you linked to:

> Thorns III cannot be directly obtained using an [enchanting table](https://minecraft.fandom.com/wiki/Enchanting_table?mobile-app=true&theme=false), but it can be obtained by using an anvil to combine two Thorns II enchantments, by [trading](https://minecraft.fandom.com/wiki/Trading?mobile-app=true&theme=false#Librarian) with villagers, or by finding an item enchanted with it from the loot chest as below.

You can get Thorns III from a villager, you just can’t get Thorns III from an enchanting table.

**Comment by ksulli** [comment]
You're right of course, I re-read the article several times before posting but still missed this :-(
