### ISSUE TITLE
Add swift sneak for boots

### ISSUE THREAD

**Issue by 1schlick** [iamcal/enchant-order#22]

**Comment by randallbruder** [comment]
Why? It isn't possible to add Swift Sneak to boots in either Java or Bedrock, and was only available on boots for a very brief time during an experimental snapshot.

**Comment by sebastianbingham** [comment]
> Why? It isn't possible to add Swift Sneak to boots in either Java or Bedrock, and was only available on boots for a very brief time during an experimental snapshot.

Based on the provided information and the elapsed time, it appears that it may be appropriate to consider resolving or closing this matter at this juncture.
