### ISSUE TITLE
[BUG] Broken on Firefox

### ISSUE THREAD

**Issue by Splarkszter** [iamcal/enchant-order#24]
Website doesn't load correctly when using Firefox Client.

![image](https://user-images.githubusercontent.com/90066319/222047247-0348963c-ef11-4c0f-944a-d3ded982b35d.png)

**Comment by sebastianbingham** [comment]
1. Can you please confirm if the issue still persists?
2. Have you tried accessing the website using a different web browser? If so, did the issue occur in the alternate browser as well?
3. What is the version of the web browser you are currently using? This information can help in understanding any potential compatibility issues.
4. Have you cleared your browser's cache and cookies? Clearing cache and cookies can sometimes resolve issues related to stored data. If you haven't tried it yet, I recommend clearing your browser's cache and cookies and then reloading the website.

**Comment by Splarkszter** [comment]
Hello! Sorry for doing such a bad issue report. Lol

On Firefox the dropdown does not display. Strange thing that I test now is that it does work using librewolf, which that could mean it's an add-on what may be causing the issue.

After disabling and enabling add-on's one by one I found out that [LocalCDN](https://www.localcdn.org/) is the thing that breaks it.

**Comment by sebastianbingham** [comment]
I am not familiar with the "workers" that @iamcal uses in their code, but if it's the same service workers that LocalCDN is talking about on their [(Test Utilities page)](https://www.localcdn.org/test/check) they recommend you turn off LocalCDN for that website.

"Service Workers essentially act as proxy servers between the website and you. It's possible that a Service Worker may deny replacements by LocalCDN. In this case, you can disable LocalCDN for this website or globally disable all ServiceWorkers:
https://www.ghacks.net/2016/03/02/manage-service-workers-in-firefox-and-chrome/"
