### ISSUE TITLE
Can't enchant sword

### ISSUE THREAD

**Issue by MrZons** [iamcal/enchant-order#25]
![Screenshot_2023-03-02-22-57-28-35_1ffb234d33525882661a5a8d47829dc1.jpg](https://user-images.githubusercontent.com/91411665/222538883-6c661dde-d1dc-41ba-b237-826224ad342a.jpg)
When I try to enchant for enchantments from the screenshot, the site crashes at step 6 of 7.

**Comment by FunMLG** [comment]
Have you tried again? It doesn't crash for me.
Anyway, here's what you were looking for:
![Screenshot_20230710_143643](https://github.com/iamcal/enchant-order/assets/44449087/e160252f-1f8e-4949-a4ad-956d131defd9)

**Comment by iamcal** [comment]
It looks like you're doing this on a phone - it requires quite a lot of memory to calculate 7 enchantments, and often crashes on phones. I'll add a warning when this is likely to happen

**Comment by iamcal** [comment]
As of [d9825f4](https://github.com/iamcal/enchant-order/commit/d9825f47cf17e20592194d0a8603cbd88f7ad99f), we now show a warning in this situation
