### ISSUE TITLE
Boots unavailable

### ISSUE THREAD

**Issue by Zeelda1564** [iamcal/enchant-order#28]
When inputting all boots enchants, the page lags, shortly before crashing. I don’t expect there to be a possible way for this to cost <40 levels though, so I assume it just overloads and can’t compute it.

**Comment by sebastianbingham** [comment]
I also received the following error "Error code: Out of Memory" when selecting the following:

![image](https://github.com/iamcal/enchant-order/assets/5107912/4f5f90c9-f87b-45b4-b16d-ca38f4bc9605)

Browser information:
https://whatismybrowser.com/w/PFZ6W5N

**Comment by ManInMyVan** [comment]
There is [a way to do it](https://preview.redd.it/yc2uf1ex7gg51.jpg?width=1500&format=pjpg&auto=webp&s=f0ec945fcb014b01e46bb8141e4820776ff99b23), it may not be optimal though

**Comment by iamcal** [comment]
With the updated algorithm, this now works
![image](https://github.com/iamcal/enchant-order/assets/173750/cf5234a6-a544-4ffa-bdcf-bf8614c10a8c)
