### ISSUE TITLE
Non Optimal Solution

### ISSUE THREAD

**Issue by TheArcaneMuse** [iamcal/enchant-order#29]
When I input this request: 

Boots with Fire Pro 4, Frost Walker 2, Feather Falling 4, Mending, Thorns 3 and Unbreaking 3 

I got a non-optimal solution that was too expensive to use. Granted, the Thorns 3 book I used was made with Thorns 1 books, but I tried another combination from another tool and I was able to enchant them there. So I think something is wrong with the suggested solution. 

![too expensive enchant](https://user-images.githubusercontent.com/98287517/231343112-44126fad-d54c-4a44-a7e6-4510cf609988.jpg)

Whereas the following solution worked:

![working solution](https://user-images.githubusercontent.com/98287517/231343282-ae7f6ebd-8f6e-4c5b-8b47-6604aa78e52d.jpg)

**Comment by iamc24** [comment]
The calculator literally says that you cannot have any prior work penalty which includes combining books for higher level enchants.

**Comment by iamcal** [comment]
The calculator only works for items with no prior work penalty, as described in the text at the top of the page.
