### ISSUE TITLE
Styled the website

### ISSUE THREAD

**Issue by LunarTaku** [iamcal/enchant-order#30]
Hello! I really liked this website but there was one thing missing. The styling is a bit outdated and so i thought i could make it look better with some rounded corners dark background and more! If you want to check the improvements i made its available at https://enchant-order.lunartaku.codes/ or the repo https://github.com/LunarTaku/enchant-order

PS: I included credits that its made by you since i only changed the style a lil bit :D 
Also if you want me to remove the repo that's okay with me since its your work.

**Comment by iamcal** [comment]
Looks great - thanks for letting me know :)
