### ISSUE TITLE
Consider PWP on final item

### ISSUE THREAD

**Issue by mattfbacon** [iamcal/enchant-order#32]
It may make no difference within the context of the algorithm, but I think a truly "optimal" solution should also optimize for the prior work penalty on the final item.

For example, consider enchanting a helmet with Thorns 3, Mending, and Unbreaking 3. The website will tell you to do (((Helmet + Thorns 3) + Mending) + Unbreaking). This costs 21 levels, which is indeed optimal. Unfortunately this results in a prior work penalty of 7 levels, which is not optimal. Consider the solution ((Helmet + Thorns 3) + (Unbreaking 3 + Mending)). This will get a prior work penalty of 3 levels.

**Comment by iamcal** [comment]
This has now been added
![image](https://github.com/iamcal/enchant-order/assets/173750/f4aa4cb8-4ee5-446b-891f-6ba3bf6ba573)

**Comment by mattfbacon** [comment]
Great, thanks. Can I confirm, though, that even when "Least XP" is selected, if multiple solutions cost the same XP, the solution with the least PWP will be selected?

**Comment by iamcal** [comment]
I'm not sure such a situation is possible 🤔

**Comment by mattfbacon** [comment]
I believe the example I gave in the initial comment is one example of such a situation.

**Comment by jmarcinik3** [comment]
Hi there! If you select "Least XP/Levels", then the solution is chosen first to minimize levels, then lower prior work can break ties. If you select "Prior Work Penalty", then the solution is chosen first to minimize prior work, then levels are minimized.

**Comment by mattfbacon** [comment]
Sounds good.
