### ISSUE TITLE
Optimal solution still brought up "Too expensive"

### ISSUE THREAD

**Issue by Blalex333** [iamcal/enchant-order#33]
I'm facing some issues with enchanting in Minecraft and I'm not sure if it's due to outdated information or my own mistakes. Despite following a guide for sword enchantments, I received a "Too expensive" message when attempting to add my final book. Additionally, the tool indicated that it would require 49 levels, but I ended up spending around 90 levels in total. It's unclear where the problem lies, but I would appreciate any help in resolving this matter.

**Comment by FunMLG** [comment]
I think you musn't combine multiple books between them. Like if you want P4 by combining two P3, it doesn't work.
I don't know if you did something similar

**Comment by iamcal** [comment]
That's correct - it assumes the starting 'work penalty' on all items is zero, so you can't combine books.

**Comment by iamcal** [comment]
This is now explained in the opening text as of commit [b518ed1](https://github.com/iamcal/enchant-order/commit/b518ed14ff667cd1e0cc15651d3a2359c9884666)
