### ISSUE TITLE
Speed and generality improvements for code

### ISSUE THREAD

**Issue by jmarcinik3** [iamcal/enchant-order#36]
Hi,

I've created a clone on my local desktop and would like to push some revisions. I am unable to publish a separate branch to this repository and unable to push to the main branch. My revisions make the code faster, add more display information, and make more of the GUI elements autogenerate solely based on the metadata file. Please enable permissions to create a separate branch and aid in getting these revisions through.

Peace,
Joey

**Comment by bo0tzz** [comment]
You need to create a fork to your own account and push the changes there, then create a pull request to merge them into this repository.

**Comment by iamcal** [comment]
https://opensource.com/article/19/7/create-pull-request-github

**Comment by jmarcinik3** [comment]
Thanks for the help, I created a pull request!
