### ISSUE TITLE
Pressing "Allow multiple Protection types (1.14.1 only)" moves some enchantments

### ISSUE THREAD

**Issue by ManInMyVan** [iamcal/enchant-order#40]
Pressing the "Allow multiple Protection types (1.14.1 only)" button moves some enchantments

Helmet/Turtle Shell:
|Before|
|:-:|
|Protection|
|Aqua Affinity|
|Blast Protection|
|Fire Protection|
|Mending|
|Projectile Protection|
|Respiration|
|Thorns|
|Unbreaking|

|After|
|:-:|
|Protection|
|Blast Protection|
|Fire Protection|
|Projectile Protection|
|Aqua Affinity|
|Mending|
|Respiration|
|Thorns|
|Unbreaking|

Chestplate:
|Before|
|:-:|
|Protection|
|Blast Protection|
|Fire Protection|
|Projectile Protection|
|Mending|
|Thorns|
|Unbreaking|

|After|
|:-:|
|Protection|
|Blast Protection|
|Fire Protection|
|Mending|
|Projectile Protection|
|Thorns|
|Unbreaking|

Leggings:
|Before|
|:-:|
|Protection|
|Blast Protection|
|Fire Protection|
|Projectile Protection|
|Mending|
|Swift Sneak|
|Thorns|
|Unbreaking|

|After|
|:-:|
|Protection|
|Blast Protection|
|Fire Protection|
|Mending|
|Projectile Protection|
|Swift Sneak|
|Thorns|
|Unbreaking|

Boots:
|Before|
|:-:|
|Protection|
|Blast Protection|
|Fire Protection|
|Projectile Protection|
|Depth Strider|
|Frost Walker|
|Feather Falling|
|Mending|
|Soul Speed|
|Thorns|
|Unbreaking|

|After|
|:-:|
|Protection|
|Blast Protection|
|Depth Strider|
|Frost Walker|
|Feather Falling|
|Fire Protection|
|Mending|
|Projectile Protection|
|Soul Speed|
|Thorns|
|Unbreaking|

**Comment by iamcal** [comment]
The purpose of the option is to ungroup the enchantments. This does re-sort the list.

I'm not sure I understand what problem you're reporting?

**Comment by iamcal** [comment]
Due to some internal changes, the ordering no longer changes when the mode is switched
