### ISSUE TITLE
Not all options are explored. (maybe intended) 

### ISSUE THREAD

**Issue by KasperErik** [iamcal/enchant-order#42]
This is more a curious question.   

I noticed that the counter saying how many options were explored doesn't equal all the unique options for 3 enchantments or more.
Are some options intentionally left out, since they will never be optimal.   

Or is something else going on?   

For 3 enchantments on an item there are 30 unique ways of combining the books and item.
But the tool claims to only explore 24.

**Comment by KasperErik** [comment]
### item + book, + book, + book

1. ((Shears + Unbreaking 3) + Mending) + Efficiency 5
2. ((Shears + Unbreaking 3) + Efficiency 5) + Mending
3. ((Shears + Mending) + Unbreaking 3) + Efficiency 5
4. ((Shears + Mending) + Efficiency 5) + Unbreaking 3
5. ((Shears + Efficiency 5) + Unbreaking 3) + Mending
6. ((Shears + Efficiency 5) + Mending) + Unbreaking 3

### item + double book, + book

1. (Shears + (Unbreaking 3 + Mending)) + Efficiency 5
2. (Shears + (Unbreaking 3 + Efficiency 5)) + Mending
3. (Shears + (Mending + Unbreaking 3)) + Efficiency 5
4. (Shears + (Mending + Efficiency 5)) + Unbreaking 3
5. (Shears + (Efficiency 5 + Unbreaking 3)) + Mending
6. (Shears + (Efficiency 5 + Mending)) + Unbreaking 3

### item + book, + double book 

1. (Shears + Unbreaking 3) + (Mending + Efficiency 5)
2. (Shears + Unbreaking 3) + (Efficiency 5 + Mending)
3. (Shears + Mending) + (Unbreaking 3 + Efficiency 5)
4. (Shears + Mending) + (Efficiency 5 + Unbreaking 3)
5. (Shears + Efficiency 5) + (Unbreaking 3 + Mending)
6. (Shears + Efficiency 5) + (Mending + Unbreaking 3)

### item + triple book, where the triple book is made by double book + book

1. Shears + ((Unbreaking 3 + Mending) + Efficiency 5)
2. Shears + ((Unbreaking 3 + Efficiency 5) + Mending)
3. Shears + ((Mending + Unbreaking 3) + Efficiency 5)
4. Shears + ((Mending + Efficiency 5) + Unbreaking 3)
5. Shears + ((Efficiency 5 + Unbreaking 3) + Mending)
6. Shears + ((Efficiency 5 + Mending) + Unbreaking 3)

### item + triple book, where the triple book is made by book + double book

1. Shears + (Unbreaking 3 + (Mending + Efficiency 5))
2. Shears + (Unbreaking 3 + (Efficiency 5 + Mending))
3. Shears + (Mending + (Unbreaking 3 + Efficiency 5))
4. Shears + (Mending + (Efficiency 5 + Unbreaking 3))
5. Shears + (Efficiency 5 + (Unbreaking 3 + Mending))
6. Shears + (Efficiency 5 + (Mending + Unbreaking 3))

**Comment by iamcal** [comment]
Yes! If two paths are found that come to the same intermediate state, then we discard the more expensive one(s).

For example:

    Path 1: a + (b + c)
    Path 2: (a + b) + c

Both paths will come to the same outcome, but will usually have different costs, so we drop the non optimal path from future combinations. This reduces the search space _significantly_.
