### ISSUE TITLE
Bug: Other language(s) behaving wierdly

### ISSUE THREAD

**Issue by cph101** [iamcal/enchant-order#52]
Example:
![Example](https://i.ibb.co/rbF36sv/Screenshot-2023-09-22-at-08-26-17.png)

This may be due to the cache IDs being the same in [`script.js`](https://github.com/iamcal/enchant-order/blob/main/script.js), the issue happens with this config:

```JavaScript
var languages = {
	//key   : ['LABEL', cache-id],
	'en'    : ['English', 1],
	'pt-BR' : ['Português', 2],
	'ru-RU' : ['Русский', 1],
	'zh-CN' : ['中文', 2],
        'nl' : ['Nederlands', 1],
};
```

Not sure if this is the problem, but it seems likely.

What also sometimes happens, is that it offers enchantments as an option which aren't available for that item, for example, Swift Sneak for chestplates and Infinity for helmets.

**Comment by cph101** [comment]
Turns out this was a human error on my part! Sorry for making a false issue. :|

**Comment by iamcal** [comment]
No worries! The cache ID is just used for forcing the browser to fetch a newer version of any individual language file - they can all safely be the same value :)
