### ISSUE TITLE
Update work penalty link for new Minecraft Wiki

### ISSUE THREAD

**Issue by fchagas97** [iamcal/enchant-order#57]
Hello!
In [recent events](https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom/First_discussion) the Minecraft Wiki contributor community has decided to move from Fandom to a new host, so I was wondering if it would be possible to update the work penalty link to the corresponding new wiki page ([https://minecraft.wiki/w/Anvil_mechanics](https://minecraft.wiki/w/Anvil_mechanics)).
Thanks in advance!

**Comment by cph101** [comment]
Perhaps. I'm sure lots of people will continue to use the fandom site, but admittedly the website does look a lot cleaner. It'll be interesting see what Cal makes of this

**Comment by iamcal** [comment]
Fixed, for all languages pointing to that page

**Comment by cph101** [comment]
The new wiki doesn't (yet) have translations, although the anvil mechanics page hasn't got very many translations in the first place.
