### ISSUE TITLE
Backgrounds of some enchantments shrink after being selected

### ISSUE THREAD

**Issue by ManInMyVan** [iamcal/enchant-order#63]
The affected ones seem to be:
- Aqua Affinity
- Channeling
- Flame
- Silk Touch
- Infinity
- Mending
- Multishot
- Curse of Vanishing
- Curse of Binding

Before:
![before](https://github.com/iamcal/enchant-order/assets/113963219/b19a3b82-93eb-4593-b304-a1cc33deeafc)
After:
![after](https://github.com/iamcal/enchant-order/assets/113963219/d60dd58c-bb69-4e8a-8ece-7496ace3abc3)

Here's both side by side:
![both](https://github.com/iamcal/enchant-order/assets/113963219/f63899e5-7cae-4122-bf44-13c6d9db5251)

**Comment by cph101** [comment]
I suspect this is is a padding issue, my fix would probably be to add:
```
.level-button.on {
    margin: 2px;
}
```
However, I have not yet encountered this bug, so it is hard to fix something that isn’t broken for me.

Also, which browser are you using? Some (notoriously firefox) mess up css properties where it would normally work perfectly fine on most browsers.

**Comment by cph101** [comment]
Your css does appear to be buggy, since the font should be something related to `sans-serif`, and the screenshot uses `serif`, aka. default browser font

**Comment by ManInMyVan** [comment]
> Also, which browser are you using?

firefox on mobile

**Comment by iamcal** [comment]
This is now fixed - it was caused my incorrect margins, and only showed up for enchants with a single level
