### ISSUE TITLE
Tridents missing Sharpness

### ISSUE THREAD

**Issue by CoolMad10** [iamcal/enchant-order#64]
You can apply Sharpness to tridents, but the calculator doesn't have the option.

**Comment by CoolMad10** [comment]
(The wiki doesn't show this, but test it in 1.20.1+ and you'll find that you can indeed add Sharpness)

**Comment by CoolMad10** [comment]
You may be able to do it in earlier versions, but this is just where I tested it.

**Comment by cph101** [comment]
Wow, that’s a big change. There have been mods based off enabling that ability, so it is most likely a bug. Still though, it would be good to mimic the game as closely as possible on this calculator

**Comment by TheWyo** [comment]
> (The wiki doesn't show this, but test it in 1.20.1+ and you'll find that you can indeed add Sharpness)

Reading this surprised me, booted up the game to check (1.20.2 specifically), and it's true, but with a caveat: Only seems to work in creative (which is curious in and of itself, does anything else do that? Creative doesn't let you do _everything_ you want, cuz you can't do infinity & mending normally in creative either). If you can't do it in survival, I think adding this to the calculator is probably a bit of a moot point, as the only time you'd care about level cost would be survival anyway.

**Comment by CoolMad10** [comment]
Did a slight bit more testing, and yep, creative only. 
Turns out it isn't just Sharpness, nor tridents, that are special. You can also add Fire Aspect to both tridents and axes.

Thanks for the correction.
