### ISSUE TITLE
Include Pre-Enchantments

### ISSUE THREAD

**Issue by kmpoppe** [iamcal/enchant-order#7]
When a pre-enchanted item comes as loot from somewhere(tm), it would be great to be able to add the existing enchantments to the target.

Example: Diamond shovel with Eff 3 Unbreaking 3, wanted to add Mending and Silk Touch. When choosing all 4 enchantments "as is" the result will be non-reachable combinations because the existing enchantments would have to be combined differently.

K

**Comment by iamcal** [comment]
When an item comes pre-enchanted, it comes with zero work-cost. As a result, you only need to add the missing enchantments (which you can already do).

**Comment by kmpoppe** [comment]
Thanks, Cal :)
