### ISSUE TITLE
Feature Request: Light up selected enchants

### ISSUE THREAD

**Issue by Earth1283** [iamcal/enchant-order#70]
Reasons to request this:

1. There is no way to tell if you selected an enchant or not
2. It isn't very clear on weather or not you selected an option, leading to repeated/missed selections

Thus, for all those players in Minecraft who suffer from poor memory trying to use this and forget what they selected, add the feature

**Comment by iamcal** [comment]
Could you share a screenshot of what’s happening? The buttons should change color when selected.

**Comment by Earth1283** [comment]
> Could you share a screenshot of what’s happening? The buttons should change color when selected.
As shown in the following attachment, the color indicator broke

https://github.com/iamcal/enchant-order/assets/142399154/607bfe85-bddc-4541-825c-7362383ee087

**Comment by iamcal** [comment]
Huh, very weird. It seems likely that you're getting a JavaScript error somewhere. Can you open developer tools (F12) and screenshot any error messages shown in the console?

**Comment by Earth1283** [comment]
It's fixed 😃
