### ISSUE TITLE
iOS Crash

### ISSUE THREAD

**Issue by littlebeagle** [iamcal/enchant-order#9]
On iOS, chrome or safari if you select boots for example and fully enchant them then the webpage crashes.

I believe it’s hitting some sort of timeout value.

**Comment by NatoBoram** [comment]
Boots also crash on Android. It gets stuck at 

> Calculating stage 6 of 7 (793,800 paths explored)

**Comment by iamcal** [comment]
Mobile clients now show a warning when there are many enchantments (6+). Additionally, the updated algorithm is _much_ more likely to complete without running out of memory.
