### ISSUE TITLE
Mace missing from item list

### ISSUE THREAD

**Issue by LordEnder-Kitty** [iamcal/enchant-order#91]
The mace was recently added and it would probably be a good idea to add support for it.

Although, the Wind Burst enchantment is **only** obtainable in survival as level 1 books from ominous vaults and **must** be combined to obtain the maximum level of 3. I'm not sure if that would cause any issues or difficulty implementing, but it should probably be acknowledged when adding it to the site.

**Comment by mdlcgithub** [comment]
heres a gif for mace icon
![mace](https://github.com/iamcal/enchant-order/assets/85042666/45d9e199-dd5b-438f-b9f7-4fa54de005ef)

**Comment by iamcal** [comment]
Added in PR #90 

There's no special treatment of Wind Burst yet - that's going to require a lot of rework in the UI
